# -*- coding: utf-8 -*-
"""We2Tech HEXTER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEFl9Jnx3JnyR8E_WTGWfr4_gzHIsJ3Y
"""

import pandas as pd
df = pd.read_csv('2015_16_Districtwise.csv')
df

df.describe()

df.iloc[621:633, 1:22]

df.iloc[210:246, 1:22]

pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.read_csv('/content/2015_16_Districtwise.csv')

df

profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':False}})

profile.to_notebook_iframe()

profile.to_file(output_file="REPORT.html")

